version: "3"
services:
  node:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: node-app
    command: sh -c "npm cache clean --force && yarn install && yarn start"
    ports:
      - "3000:3000"
    restart: always
    tty: true
volumes:
  node-data:
